### PR TITLE
Fix custom mpi flags

### PR DESCRIPTION
**Pull request by cimes-isi**
I ran into similar issues as @Infinoid in https://github.com/BachiLi/Halide/pull/2 and it was a pain to resolve.

This first fixes how we parse MPI flags for our custom command, and generalizes it so "extra" flags can be extended as needed.  I had issues with multiple flags being quoted which clang obviously doesn't like, e.g., "-fexceptions -pthread" is not a valid flag.  In short, it's cleaner to use lists explicitly which is what the args are for `add_custom_command`.

I then also had to fix mpi.h looking for C++ headers.  It turns out FindMPI [1] has a way to do this using `MPI_CXX_SKIP_MPICXX`.  It also appears that this *must* be a CACHE variable, otherwise it was being ignored the first time I ran `cmake` but was detected if cmake was run more than once.  This solution should be portable to a number of different MPI implementations that FindMPI supports.  [1] documents this in terms of MPI-2, but it seems to be more general than that.

[1] https://cmake.org/cmake/help/latest/module/FindMPI.html

### CODE REVIEW

**Comment by Infinoid** [comment]
It sounded like you weren't seeing this problem a couple of weeks ago.  I'm curious, what changed?

**Comment by cimes-isi** [comment]
Different platform (USC Discovery cluster)

**Comment by cimes-isi** [comment]
I'm also wondering if life would be easier if we link against `MPI::MPI_C` instead of `MPI:MPI_CXX`.  Conceptually we shouldn't need anything C++ from MPI I think.

**Comment by Infinoid** [comment]
Note that some people build Halide with `make`, not `cmake`, so that will need to be tested before merging distributed back into upstream master.

**Pull request merged**
