### PR TITLE
Add -DOMPI_SKIP_MPICXX flag to mpi runtime bytecode build flags

### PR DESCRIPTION
**Pull request by Infinoid**
Without this, building initmod.mpi_32.ll and initmod.mpi_64.ll
try to pull in a bunch of C++ headers and things end badly.

### CODE REVIEW

**Comment by cimes-isi** [comment]
-1 from me.  This is a MPI compiler-specific problem, and I don't think we really understand where this problem is coming from.

Applying the flags discovered through FindMPI may not be entirely appropriate to apply to a custom shell command here.  I'm not sure what a better alternative is at the moment though.  I suggest we clean up (i.e., narrow) the MPI targeting in the dist Halide cmake files first - we've seen in the SAR app that we have to add MPI flags to targets when, if handled correctly, such dependencies should be picked up automatically/transitively.  For example, this shotgun approach is not ideal:

```cmake
    add_definitions(${MPI_CXX_COMPILE_FLAGS})
    include_directories(${MPI_CXX_INCLUDE_DIRS})
    link_directories(${MPI_CXX_LIBRARY_DIRS})
```

That said, this problem appears different due to the use of a custom command, but there is an off-chance cleaning up cmake makes this go away.

**Comment by cimes-isi** [comment]
I also see that the flag parsing here is looking at CXX flags, but the custom command is using `clang` and not `clang++`.  So simply fixing the parsing to use `MPI_C_COMPILE_FLAGS` and `MPI_C_INCLUDE_DIRS` instead might solve this problem.

I am also concerned that simply calling `clang` might actually end up using the wrong `clang`, but that's a different issue.

**Comment by Infinoid** [comment]
> I don't think we really understand where this problem is coming from.

Feel free to dig in and figure it out.  Here's how to reproduce it in 5 minutes.

Spawn a docker container or VM or something with ubuntu 20.04, then build inside the container.

If you use docker, here's the command to spin it up: `docker run -it --rm ubuntu:20.04 bash`

Once you are sitting in a fresh install, run these commands:

```sh
apt update
DEBIAN_FRONTEND=noninteractive apt-get -y install gpg sudo wget lsb-release software-properties-common apt-transport-https

# get new cmake
wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
echo deb https://apt.kitware.com/ubuntu/ `lsb_release -cs` main >/etc/apt/sources.list.d/cmake.list

# get new llvm/clang
bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

# install build deps
DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential cmake git libopenmpi-dev clang-11 llvm-11-dev llvm-11-runtime clang-tools-11 libclang-11-dev zlib1g-dev

# get sources
git clone https://github.com/bachili/halide -b distributed

# configure and build
mkdir build; cd build
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DTARGET_WEBASSEMBLY=OFF -DWITH_PYTHON_BINDINGS=OFF ../halide
make
```

This will result in the following output:

```
[...]
[ 15%] Generating initmod.module_jit_ref_count_64.ll
[ 15%] Generating initmod.module_jit_ref_count_64.bc
[ 15%] Generating _initmod_module_jit_ref_count_64.cpp
[ 15%] Generating initmod.module_jit_ref_count_64_debug.ll
[ 15%] Generating initmod.module_jit_ref_count_64_debug.bc
[ 15%] Generating _initmod_module_jit_ref_count_64_debug.cpp
[ 15%] Generating initmod.mpi_32.ll
In file included from /halide/src/runtime/mpi.cpp:3:
In file included from /usr/lib/x86_64-linux-gnu/openmpi/include/mpi.h:2868:
/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/ompi/mpi/cxx/mpicxx.h:42:10: fatal error: 'map' file not found
#include <map>
         ^~~~~
1 error generated.
make[2]: *** [src/runtime/CMakeFiles/Halide_initmod.dir/build.make:4400: src/runtime/initmod.mpi_32.ll] Error 1
make[1]: *** [CMakeFiles/Makefile2:2354: src/runtime/CMakeFiles/Halide_initmod.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
```

You can use these instructions to reproduce it in ubuntu 18.04 and 16.04 if you want, but you may have to remove older versions of clang; cmake doesn't always choose the latest one.

**Comment by cimes-isi** [comment]
I was looking at this a bit more.  I see that in the Makefile, `RUNTIME_CXX_FLAGS` specifies `-std=c++11`, whereas in cmake, no standard is set here, so `clang` may be defaulting to standard C behavior.  Specifying the standard may force `clang` to use the correct C++ include paths, which would be consistent with using other CXX flags.

Note also that the top-level CMakeLists requires `c++14` rather than `c++11`.

**Comment by Infinoid** [comment]
Closed in favor of #5.

**Pull request closed without merging**
